### PR TITLE
Ensure that `EnvVarCombineMergeUnique` keeps order

### LINKED ISSUE #42: The order of $PATH is not guaranteed
### Bug description

The order of `$PATH` is not guaranteed. This will, for example, randomly determine which takes precedence when python is installed on both pyenv and the system.
https://github.com/gitpod-io/dazzle/blob/7a3bd09f878ba25057d94743ec42c9f0d64bf992/pkg/dazzle/combiner.go#L342-L345
related: 
- https://github.com/gitpod-io/workspace-images/issues/694
- https://github.com/gitpod-io/workspace-images/issues/664

### Steps to reproduce

I couldn't figure out how to actually run dazzle to be sure, but I can see that there is no order guarantee for `map[string][string]`.
https://go.dev/play/p/XcEBRuUmXZy

### Expected behavior

The order of `$PATH` is guaranteed to be in the order of base -> others.

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by utam0k**
## Description

This pr resolves an issue where the order of env vars would be random when merging them
If there are the same env var, the latter will be given priority.

## Related Issue(s)

Fixes #42

## How to test
There are two ways to confirm the behavior
### Unit test
```console
$ go test -v ./...
```

### Create an actual image

Create the following files to create the image.

`base/Dockerfile`
```Dockerfile
FROM ubuntu:latest
```
`chunks/golang/Dockerfile`
```Dockerfile
ARG base
FROM ${base}

RUN mkdir -p /root/go/bin
ENV PATH=/root/go/bin:$PATH
```
`chunks/pyenv/Dockerfile`
```Dockerfile
ARG base
FROM ${base}

RUN mkdir -p /root/.pyenv/bin /root/.pyenv/shims
ENV PATH=/root/.pyenv/bin:/root/.pyenv/shims:$PATH
```
`dazzle.yaml`
```yaml
combiner:
  combinations:
  - name: full
    ref: []
    chunks:
    - pyenv
    - golang
  envvars:
    - name: PATH
      action: merge-unique
```

Re-create the image several times to make sure the PATH remains constant.
```console
$ docker run --rm localhost:5000/test:full env | grep PATH
PATH=/root/.pyenv/bin:/root/.pyenv/shims:/root/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

## Release Notes

```release-note
Ensure that EnvVarCombineMergeUnique keeps order
```

### CODE REVIEW

File: pkg/dazzle/combiner.go [hunk 1]
```diff
@@ -311,14 +311,21 @@ func mergeEnv(base *ociv1.Image, others []*ociv1.Image, vars []EnvVarCombination
...
+							flags[entry] = true
+							vss = append(vss, entry)
+						}
 					}
-					vs[v] = struct{}{}
-					vss := make([]string, 0, len(vs))
-					for s := range vs {
-						vss = append(vss, s)
+					for i, j := 0, len(vss)-1; i < j; i, j = i+1, j-1 {
+						vss[i], vss[j] = vss[j], vss[i]
```
Comment (csweichel) [inline pkg/dazzle/combiner.go:328]: The original code is simple to modify for sort order. All it takes is a `sort.Strings` before joining the values
```Go
sort.Strings(vss)
envs[k] = strings.Join(vss, ":")
```

File: pkg/dazzle/combiner_test.go [hunk 2]
```diff
@@ -0,0 +1,185 @@
...
+		if err != nil {
+			t.Fatal(err)
+		}
+		if len(envs) != len(test.expect) {
+			t.Fatal("unexpected length", len(envs))
+		}
+		for i, env := range envs {
+			if env != test.expect[i] {
+				t.Fatal("unexpected env", envs)
+			}
```
Comment (csweichel) [inline pkg/dazzle/combiner_test.go:181]: Thank you very much for writing the test! 🚀 
By (still undocumented) convention, we use `go-cmp` for unit tests, e.g. here:
https://github.com/gitpod-io/dazzle/blob/949a695eb26b335f266839bfb2b10e60c3336a27/pkg/dazzle/project_test.go#L129-L131

**Comment by csweichel** [comment]
@utam0k I took the liberty and pushed a commit onto the branch which imho simplifies the code a bit. Now, the order is determined by the image order followed by first occurence.

File: pkg/dazzle/combiner_test.go [hunk 3]
```diff
@@ -72,36 +73,36 @@ func TestMergeEnv(t *testing.T) {
 					Action: EnvVarCombineMergeUnique,
 				},
 			},
-			expect: []string{"PATH=first:second:third:fourth:fifth:sixth:seventh:eighth:$PATH"},
+			expect: []string{"PATH=first:second:third:common-value:fourth:fifth:sixth:seventh:eighth"},
```
[the remark this answers is not in the document]
Comment (csweichel) [reply pkg/dazzle/combiner_test.go:76]: That consideration/example makes a lot of sense. It seemed to me that special handling of "common values" was hard to understand. Now, it's easy to communicate in which order the entries end up.

We could consider reversing the order though, which is pretty much what your original version did :D 

I.e. looping like:
```Go
lenVS := len(vs) - 1
for i := range vs {
  // segment order = reverse(chunk order)
  v := vs[lenVS - i]
```

**Comment by utam0k** [comment]
@csweichel PTAL

**Review by csweichel — APPROVED** [review]
Awesome. Works as intended :)
